spring:
  application.name: "sb3-ss6-security-user-role-jjwt"
  datasource:
    url: "jdbc:mysql://localhost:3306/db_security"
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database: mysql

logging:
  level:
    org:
      hibernate:
        SQL: debug


secret-key: secret